set export

_default:
    @just --list

cross_engine:="docker"
available_target := "x86_64 aarch64"

_should_x_compile target="x86_64":
    @[ "$(uname -m)" = {{target}} ]&& echo false || echo true


_check_target t :
    @for x in {{available_target}};do if [ "$t" = "$x" ];then found=1;break;else found=0 ;fi;done &&\
    if [ $found = 0 ];then echo "$t should belong to authorized values: {{available_target}} " && exit 1;fi

_clean crate_path:
    @echo "cleaning"
    @rm -rf {{crate_path}}/target
    @rm -f {{crate_path}}/build.rs
    @rm -f {{crate_path}}/Cross.toml

_trim_cross_vars args:
    @echo $args| sed 's/--env //g'

_x_compile bin_name="" crate_path="" target="x86_64" build_vars= "":
    @just _check_target {{target}}
    @echo "installing dependencies"
    @cargo install cross --git https://github.com/cross-rs/cross
    @if [ -e ./x_build_utils/Cross_{{target}}.toml ];then cp ./x_build_utils/Cross_{{target}}.toml {{crate_path}}/Cross.toml;fi
    @echo "start x compilation with cross to target $target"
    @cd {{crate_path}} && CROSS_CONFIGCROSS_CONTAINER_ENGINE={{cross_engine}} CROSS_CONTAINER_OPTS="{{build_vars}}"  cross build --target {{target}}-unknown-linux-gnu --release -v
    @echo "run post install scripts with cross"
    @cp ./x_build_utils/build.rs {{crate_path}}
    @cd {{crate_path}} && CROSS_CONFIGCROSS_CONTAINER_ENGINE={{cross_engine}} CROSS_CONTAINER_OPTS="{{build_vars}}"  cross build --target {{target}}-unknown-linux-gnu --release 
    @cp  {{crate_path}}/target/{{target}}-unknown-linux-gnu/release/{{bin_name}}_{{target}}.bin ./src/bins/{{bin_name}}_{{target}}.bin
    @just _clean {{crate_path}}
  

_compile  bin_name="" crate_path=""  build_vars= "":
    @echo "start  compilation  to target $target"
    @cd {{crate_path}} && eval "$(just _trim_cross_vars "{{build_vars}}")" && cargo build --release
    @strip -s --strip-unneeded   {{crate_path}}/target/release/{{bin_name}}
    @objcopy -O binary {{crate_path}}/target/release/{{bin_name}} ./src/bins/{{bin_name}}_$(uname -m).bin
    @just _clean {{crate_path}}

build  bin_name="" crate_path="" target="x86_64"  build_vars= "":
    @just _check_target {{target}}
    @if [ "$(just _should_x_compile $target)" = "true" ];\
        then just _x_compile {{bin_name}} {{crate_path}} {{target}} "{{build_vars}}";\
        else just _compile {{bin_name}} {{crate_path}} "{{build_vars}}" ;\
    fi
